# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-rnaseq-1.4.2
channels:
  - conda-forge
  - bioconda
  - defaults
  - conda-forge/label/broken
  - conda-forge/label/noarch
  - bioconda/label/cf201901
  - bioconda/label/noarch
  
  
  
dependencies:
  ## conda-forge packages, sorting now alphabetically, without the channel prefix!
  - matplotlib-base=3.3.2
  - markdown=3.2.2
  - r-base=4.0.2
  - r-base64enc=0.1_3
  - r-data.table=1.12.8
  - r-gplots=3.1.0
  - r-markdown=1.1
  - python=3.8.5  
  - pymdown-extensions=8.0
  - pygments=2.7.1
  - pigz=2.3.4

  ## bioconda packages, see above
  - bioconductor-dupradar=1.18.0
  - bioconductor-edger=3.30.0
  - bioconductor-rsamtools=2.4.0
  - bioconductor-rsubread=2.2.1
  - bioconductor-summarizedexperiment=1.18.1
  - bioconductor-tximeta=1.6.2
  - deeptools=3.5.0
  - deeptoolsintervals=0.1.9
  - diamond=0.9.14
  - fastqc=0.11.9
  - gffread=0.12.1
  - hisat2=2.2.1
  - hmmer=3.3.1
  - matplotlib-base=3.3.2
  - multiqc=1.9
  - picard=2.23.4
  - preseq=2.0.3
  - qualimap=2.2.2d
  - r-base64enc=0.1_3
  - r-base=4.0.2
  - r-data.table=1.12.8
  - r-gplots=3.1.0
  - r-markdown=1.1
  - rsem=1.3.3
  - rseqc=4.0.0
  - salmon=0.6.0
  - samtools=1.10
  - skewer=0.2.2
  - sortmerna=4.2.0
  - star=2.6.1d
  - stringtie=2.1.2
  - subread=2.0.1
  - umi_tools=1.0.1
  - transdecoder=5.5.0
  - trim-galore=0.6.6
  - trinity=2.1.1
  
